// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cohmmosrgcrkbcxoobbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvaG1tb3NyZ2Nya2JjeG9vYmJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5Njg1NDAsImV4cCI6MjA2NzU0NDU0MH0.2TreYwfDduabLIZrQUmZUpVAP-8WQbgVYC1nj9_-RYc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});